[workspace]
members = [
    "qoqo-quest",
    "roqoqo-quest",
    "quest-sys",
]

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"

[patch.crates-io]
roqoqo = {git="https://github.com/HQSquantumsimulations/qoqo.git", branch="1.1.0"}
qoqo = {git="https://github.com/HQSquantumsimulations/qoqo.git", branch="1.1.0"}