name: manual_build_maturin_linux

on:
  workflow_dispatch:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      deploy:
        description: "Determines if build python wheels should be deployed to PyPi"
        required: false
        default: false
        type: boolean
      build_for_arm:
        description: "Determines python wheels are also build for aarch64"
        required: false
        default: false
        type: boolean

jobs:

  build_maturin_builds_linux:
    name: maturin_build-linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          manylinux: 2014
          args: --find-interpreter --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  build_maturin_builds_linux_arm:
    name: maturin_build-linux-arm
    if: ${{inputs.build_for_arm}}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          manylinux: 2014
          target: aarch64-unknown-linux-gnu
          args: --find-interpreter --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  build_maturin_src_builds_linux:
    name: maturin_build-src
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: sdist
          args: --out wheels -m ${{inputs.py_interface_folder}}/Cargo.toml
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  deploy:
    if: ${{inputs.deploy}}
    needs: [build_maturin_src_builds_linux, build_maturin_builds_linux_arm, build_maturin_builds_linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/download-artifact@v3
      with:
        name: wheels
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install twine
        python -m twine upload --skip-existing *

